Design liste des talks
aperowebnancy/aperowebnancy-website pull request #48
Opened 2020-10-02 12:02 UTC by aymericingargiola

https://github.com/aperowebnancy/aperowebnancy-website/issues/46

Ajout du support de sass pour faire des choses custom/avancée en css et amélioration du design de la liste des talks

![image](https://user-images.githubusercontent.com/49032117/94920975-a47b4380-04b7-11eb-8b33-758856175039.png)

2020-10-05 12:07 UTC, zyhou commented
Merci pour ta contribution :smiley: 

Je trouve que c'est en effet une bonne idée de mettre un syteme de card sur X colonnes. Il y a tellement peu d'informations que mettre un talk par ligne n'est pas vraiment nécessaire. Mettre la date et le numéro d'edition (le #80) au dessus du titre est une bonne idée. J'aime beaucoup ta proposition de mettre le prochain talk sur une ligne, cela fait bien ressortir l'event. Bien joué le fait de gérer "prochainement" et "aujourd'hui" :+1: 

Les gouts et les couleurs c'est toujours un sujet sensible, je trouve le rouge peut etre trop rouge pour la date/numéro d'édition. Tu en penses quoi? Je sais bien que pour l'instant nous avons pas vraiment d'identité visuelle...

Les border (box-shadow) sont un peu trop forte, j'ai l'impression que c'est un background au niveau de la liste. Entre les cartes on vois un petit cercle blanc. Peut etre essayer avec un rouge plus légé.
![image](https://user-images.githubusercontent.com/2212144/95075120-f4ecde00-070f-11eb-8ef5-4bda171c46d9.png)

Si tu peux mettre un label sur ta PR (WIP pour dire en cours, et RFR pour dire PR qui peut etre merge), ou tu peux mettre une todolist dans la description de ta PR. N'hésite pas à me mettre en reviewer une fois la PR ready.

Une fois cette PR mergé, je peux t'ajouter en tant que contributeur si cela t'interesse, tu n'auras plus besoin de faire de fork pour proposer une PR.

Super travail en tout cas :clap: :clap:

2020-10-05 12:07 UTC, zyhou requested changes

2020-10-05 12:07 UTC, zyhou commented on styles/sass/components/talks-list.scss
> +        &.next-talk {
Le `next-talk` et le `current-talk`, est-ce qu'il y a une raison que je ne vois pas de différencier les deux ? Meilleur nommage?

2020-10-05 12:07 UTC, zyhou commented on pages/talks.js
> +                                new Date() - new Date(date) < 0
Tu pourras utiliser les variables un peu plus bas ce qui va simplifier les conditions. (ligne 57 et 64 et 121)

2020-10-05 12:07 UTC, zyhou commented on pages/talks.js
> +                                        {new Date() - new Date(date) < 0 && (
Le prochainement et le Aujourdh'ui ont le meme comportement si je ne me trome pas. Tu pourrais mettre la condition du text directement dans le ` <span>Prochainement</span>`

Si on reprend avec plus ca pourrait donner:
```js
const statusTalk = isNextTalk ? "Prochainement" : isCurrentTalk ? "Aujourd'hui" : null;
//....
<span>{statusTalk}</span>
```

2020-10-05 14:27 UTC, aymericingargiola commented on pages/talks.js
> +                                new Date() - new Date(date) < 0
Beaucoup plus lisible de cette façon en effet

2020-10-05 14:29 UTC, aymericingargiola commented on styles/sass/components/talks-list.scss
> +        &.next-talk {
Pour le moment aucune différence css mais ils ont une classe différente, je vais changer ça pour une classe commune en plus de la classe différente ça sera plus propre !

2020-10-05 14:29 UTC, aymericingargiola commented on pages/talks.js
> +                                        {new Date() - new Date(date) < 0 && (
Plus propre et plus lisible de cette façon oui

2020-10-05 14:36 UTC, aymericingargiola commented on package.json
> +        "sass": "^1.26.11"
L'idée d'avoir du sass c'est justement que ce sera plus facile à maintenir que faire du simple css pour certaines choses custom non dispo dans tailwind et ne pas se limiter (Mais tout en privilégiant ce qu'il est possible de faire avec tailwind dans le html et non dans le sass). Si on change quelque chose dans la config de tailwind ça sera facilement modifiable également dans les variables impactées du sass (comme les couleurs ou les breakpoints).
Tout est pensé pour que le sass se colle à tailwind !

2020-10-05 15:35 UTC, aymericingargiola commented
Update (https://github.com/aperowebnancy/aperowebnancy-website/pull/48/commits/638eb9c0d8562d557492e65c5223d0681524d829)
Design : Moins de rouge, box-shadow rouge sans hover uniquement pour les talks du jour/à venir + texte plus gros.

Code : Réécriture selon tes préconisations @zyhou  

![image](https://user-images.githubusercontent.com/49032117/95100003-ec58cf80-0730-11eb-83fc-4c1e7da93309.png)

2020-10-05 16:27 UTC, zyhou approved these changes

2020-10-06 16:26 UTC, zyhou commented
Vue avec @aymericingargiola je vais corriger les tests dans la prochaine PR. 

Encore merci pour ta contribution

2020-10-06 16:27 UTC, merged

2020-10-06 16:46 UTC, zyhou commented
@all-contributors please add @aymericingargiola  for code, a11y